### ISSUE TITLE
could not get it to run

### ISSUE THREAD

**Issue by diamondbarcode** [domcross/home_surveillance#2]
i am glade you pick up this project and i hope i can get some help .. i try build everything as description on Jetson Xavier Agx but i could not get it to work i stuck here ..

I am new to this area .. 

jetson@jetson-agx:~/home_surveillance/system$ python3 WebApp.py
WebApp.py:20: ExtDeprecationWarning: Importing flask.ext.uploads is deprecated, use flask_uploads instead.
  from flask.ext.uploads import UploadSet, configure_uploads, IMAGES
Traceback (most recent call last):
  File "WebApp.py", line 20, in <module>
    from flask.ext.uploads import UploadSet, configure_uploads, IMAGES
  File "/home/jetson/.local/lib/python3.6/site-packages/flask/exthook.py", line 96, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/home/jetson/.local/lib/python3.6/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/home/jetson/.local/lib/python3.6/site-packages/flask_uploads.py", line 26, in <module>
    from werkzeug import secure_filename, FileStorage
ImportError: cannot import name 'secure_filename'

**Comment by domcross** [comment]
Did you install the [requirements.txt](https://github.com/domcross/home_surveillance/blob/master/requirements.txt) by `pip3 install -r requirements.txt`?

**Comment by diamondbarcode** [comment]
yes i did. Maybe because i am on jetpack 4.4 xavier agx ?

**Comment by domcross** [comment]
That came to my mind as well, as I did try my code on Jetson Nano with JetPack 4.3 and OpenCV 4.2.0 only so far. But your message hints at a problem inside Flask, maybe you can try another Flask version?

To be honest with you I did not touch this project for some time now... my practical use-case was identifying the person who stole a weekly magazin on a regular basis, but it turned out it was just a lazy delivery guy and we change to a digital subscription ;-)

**Comment by diamondbarcode** [comment]
i reflash my system and try again .. i try 

jetson@agx:~/home_surveillance$ pip install requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt


yes i try install and Flask i found with google unless i install wrong one ..

**Comment by diamondbarcode** [comment]
i made a few change to code just commit it to make it work with jetpack 4.4 opencv 4.4 with cuda so far i just manager to get web GUI to work ... i could not add any camera or anything .. maybe this beyond my knowledge of python and this AI thing ...

But it is cool to get this to work just 1 or 2 camera ..
